### PR TITLE
Add docs badge to README

### PR DESCRIPTION
**Pull request by rrrene**
Hi there,

you have recently tried to evaluate this project via Inch. I took the liberty to make a badge for you: [Inline docs](http://inch-ci.org/github/sagiegurari/node-go-require)

The badge shows an evaluation by [InchJS](http://trivelop.de/inchjs), but I guess you already knew that. :wink: 

I would really like to roll out support for JS over the coming weeks (early adopters are [forever](https://github.com/foreverjs/forever), [node-sass](https://github.com/sass/node-sass) and [Shipit](https://github.com/shipitjs/shipit)).

Although this is "only" a passion project, I really would like to hear your thoughts, critique and suggestions. Your status page is http://inch-ci.org/github/sagiegurari/node-go-require

What do you think?

### CODE REVIEW

**Comment by sagiegurari** [comment]
actually wanted to see how your tool checks documentation.
I didn't see anywhere in your website that you support jsdoc which is the standard doc solution for javascript but testing the link you just provided seems to show that it does.

as for the tool itself, it is really nice. It does handle an area which many ignore - documentation.
i can see my docs in your website and it links strait to the file which is really cool.
but you do have an issue with stability of your website, meaning the link doesn't work every time.
also the docs are not formatted, they are the original format that is in the code.
i know it might be tricky to parse every type of documentation, but it would be nice to see it formatted correctly (for example: https://github.com/sagiegurari/node-go-require/blob/master/docs/api.md)

Once you add official support for jsdocs and the site will be more stable, than i'll add the badge.
I added a watch on your project to see when that happens.

overall, I think it is a great idea and I hope you will continue to enhance it.
it definitely has a place in the world of continue integration tools available for open source projects.

**Comment by rrrene** [comment]
Thanks for your encouragement :+1:

> but you do have an issue with stability of your website, meaning the link doesn't work every time.

Could you elaborate on this? Do you mean the [status page](https://github.com/sagiegurari/node-go-require/blob/master/docs/api.md)? Does is not load and time out? Or does it give an error?

**Comment by sagiegurari** [comment]
I meant that this page: http://inch-ci.org/github/sagiegurari/node-go-require sometimes gives me page not found errors. when i do refresh, it loads up good. strange.

by the way make sure you set the cache headers for your badges.
see: https://github.com/github/markup/issues/224

**Comment by rrrene** [comment]
I guess that was the page Lighttpd serves when I restart the Unicorn. I should put a better message there like "There is currently an update being deployed. Check back in 10 seconds!"

As for the *-Headers: Great catch, thanks!

**Comment by sagiegurari** [comment]
implemented. works good.

**Pull request closed without merging**
